sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t jaredzhang09/multiapp ./client

script:
    - docker run -e CI=true jaredzhang09/multiapp npm run test -- --coverage
