sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t jaredzhang09/multi-app ./client

script:
    - docker run -e CI=true jaredzhang09/multi-app npm run test -- --coverage

after_success:
    - docker build -t jaredzhang09/multi-client ./client
    - docker build -t jaredzhang09/multi-server ./server
    - docker build -t jaredzhang09/multi-worker ./worker
    - docker build -t jaredzhang09/multi-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jaredzhang09/multi-client
    - docker push jaredzhang09/multi-server
    - docker push jaredzhang09/multi-worker
    - docker push jaredzhang09/multi-nginx